### ISSUE TITLE
Problem with test.py

### ISSUE THREAD

**Issue by xTobs** [hasanhuz/SpanEmo#6]
Hey @hasanhuz!
I am a student and want to use your state of the art model for a school project, to analyze emotions in tweets and customer reviews.
Whenever i run the train.py file on GoogleColabs, i received the following error: 

`Traceback (most recent call last):
  File "/content/SpanEmo_MLEC/scripts/test.py", line 442, in <module>
    args = docopt(__doc__)
  File "/usr/local/lib/python3.7/dist-packages/docopt.py", line 558, in docopt
    DocoptExit.usage = printable_usage(doc)
  File "/usr/local/lib/python3.7/dist-packages/docopt.py", line 466, in printable_usage
    usage_split = re.split(r'([Uu][Ss][Aa][Gg][Ee]:)', doc)
  File "/usr/lib/python3.7/re.py", line 215, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object`

i am not very comfortable with Python and don't know whats wrong.
Preprocessing and model creation went well so far
Appreciate your help a lot!

T

**Comment by xTobs** [comment]
Problem solved with

`!HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \`

Thank you anyways!
